[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
solc = '0.8.22'
remappings = []
fs_permissions = [{ access = "read-write", path = "./reports" }]
metadata = 'none'
ffi = true
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200

[profile.linea]
evm_version = 'london'

[profile.zksync]
src = 'zksync/src'
test = 'zksync/tests'
libs = ['lib']
solc = '0.8.20'
fs_permissions = [{ access = "write", path = "./reports" }]
ffi = true
evm_version = 'shanghai'
bytecode_hash = 'none'

[profile.zksync.zksync]
compile = true
fallback_oz = true
mode = '3'
zksolc = '1.5.3'
bytecode_hash = 'none'

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"
zkevm = "${RPC_ZKEVM}"
gnosis = "${RPC_GNOSIS}"
bnb = "${RPC_BNB}"
celo = "${RPC_CELO}"
scroll = "${RPC_SCROLL}"
zksync = "${RPC_ZKSYNC}"
linea = "${RPC_LINEA}"


[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY_MAINNET}", chain = 1 }
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}", chain = 10 }
avalanche = { key = "${ETHERSCAN_API_KEY_AVALANCHE}", chain = 43114 }
polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}", chain = 137 }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", chain = 42161 }
metis = { key = "any", chain = 1088, url = 'https://api.routescan.io/v2/network/mainnet/evm/1088/etherscan' }
base = { key = "${ETHERSCAN_API_KEY_BASE}", chain = 8453 }
gnosis = { key = "${ETHERSCAN_API_KEY_GNOSIS}", chain = 100 }
scroll = { key = "${ETHERSCAN_API_KEY_SCROLL}", chain = 534352 }
bnb = { key = "${ETHERSCAN_API_KEY_BNB}", chain = 56 }
zksync = { key = "${ETHERSCAN_API_KEY_ZKSYNC}", chain = 324 }

# See more config options https://github.com/gakonst/foundry/tree/master/config
